FROM node:14.5.0-buster

USER root
ENV USER_ID=1300
RUN usermod -u $USER_ID node
RUN mkdir -p /home/node/cypherpost.io/app
RUN mkdir -p /home/node/winston && mkdir /home/node/.keys
RUN chown -R node /home/node/cypherpost.io/app /home/node/.keys
RUN npm install -g typescript mocha ts-node

USER node
WORKDIR /home/node/cypherpost.io/app
COPY --chown=node:node package*.json ./
RUN npm install
COPY --chown=node:node . .
RUN tsc

ENV MOLTRES_PORT="1112"
ENV KEY_PATH="/home/node/.keys/"
#------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------
VOLUME ["/home/node/.keys","/home/node/winston"]
EXPOSE $APP_PORT
CMD ["npm", "start"]
#------------------------------------------------------------------------------------
