#------------------------------------------------------------------------------------
FROM node:14.5.0-buster
#------------------------------------------------------------------------------------
USER root
ENV USER_ID=1000
RUN apt-get update
RUN apt-get install -y coreutils build-essential software-properties-common cmake apt-transport-https ca-certificates curl gnupg dirmngr unzip expect jq

RUN npm install -g typescript mocha ts-node npm@latest

RUN usermod -u $USER_ID node
RUN mkdir -p /home/node/cypherpost.io/app /home/node/.keys

RUN chown -R node /home/node/cypherpost.io/app /home/node/.keys
WORKDIR /home/node/cypherpost.io/app/

#------------------------------------------------------------------------------------
USER node

ENV MOLTRES_PORT="1112"
ENV TEST_PORT="1113"
ENV KEY_PATH="/home/node/.keys/"
#------------------------------------------------------------------------------------
VOLUME ["/home/node/cypherpost.io/app", "/home/node/.keys"]
EXPOSE $APP_PORT
CMD ["npm", "start"]
#------------------------------------------------------------------------------------