version: '3.7'

services:
  node:
    build:
      context: ../../app
      dockerfile: Dockerfile.dev
    image: stackmate-node-ts
    container_name: cpio-website
    restart: unless-stopped
    environment:
      - APP_PORT=1112
    ports:
      - "1112:1112"
    volumes:
      - cpio-server-code:/home/node/cypherpost.io/app
      - cpio-server-keys:/home/node/.keys
    networks:
      - cypherpostionetwork

  nginx:
    build:
      context: ../../infra/nginx
      dockerfile: Dockerfile.dev
    image: stackmate-nginx
    container_name: cpio-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cpio-web-root:/var/www/html
      - ../../infra/nginx/dev/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - node
    networks:
      - cypherpostionetwork

volumes:
  cpio-server-code:
    driver: local
    driver_opts:
      type: none
      device: $REPO
      o: bind
  cpio-server-keys:
    driver: local
    driver_opts:
      type: none
      device: $KEYS
      o: bind
  cpio-server-logs:
  cpio-datadb:
  cpio-configdb:
  cpio-web-root:

networks:
  cypherpostionetwork:
    driver: bridge
